SET SERVEROUTPUT ON;

CREATE OR REPLACE FUNCTION CHECK_SALARY(
    ID IN NUMBER
)
RETURN BOOLEAN
IS
   EMP_SALARY       EMPLOYEES.SALARY%TYPE;
 
BEGIN
    --RETRIEVE EMPLOYEE'S SALARY
    SELECT SALARY
    INTO EMP_SALARY
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = ID;

    IF EMP_SALARY > 20000 THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;

END CHECK_SALARY;



create or replace FUNCTION CHECK_SALARY_VARCHAR2(
    ID IN NUMBER
)
RETURN VARCHAR2
IS
   EMP_SALARY       EMPLOYEES.SALARY%TYPE;

BEGIN
    --RETRIEVE EMPLOYEE'S SALARY
    SELECT SALARY
    INTO EMP_SALARY
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = ID;

    IF EMP_SALARY > 13000 THEN
        RETURN ('This salary is valid');
    ELSE
        RETURN ('This salary is not valid');
    END IF;

END CHECK_SALARY_VARCHAR2;
