SET SERVEROUTPUT ON;

DECLARE
    --DECLARE THE CURSOR
    CURSOR EMPLOYEE_CURSOR IS 
        SELECT * FROM EMPLOYEES;

    --DECLARE THE ROWTYPE OF EMPLOYEE
    EMP_RECORD   EMPLOYEES%ROWTYPE;

BEGIN
    --OPEN THE CURSOR
    OPEN EMPLOYEE_CURSOR;

    --AND WE FETCH ALL DATAS FROM THE CURSOR
    LOOP
        --WE FETCH DATA FROM CURSOR AND INSERT INTO EMP_RECORD
        FETCH EMPLOYEE_CURSOR INTO EMP_RECORD;
    
        --AND WE TEST IF DATA NOT FOUND , WE EXIT LOOP
        EXIT WHEN EMPLOYEE_CURSOR%NOTFOUND; 
        
        --DISPLAY THE EMPLOYEES
        DBMS_OUTPUT.PUT_LINE('EMPLOYEE : ' || EMP_RECORD.FIRST_NAME || ' '|| EMP_RECORD.LAST_NAME);
    END LOOP;
    
    --CLOSE THE CURSOR
    CLOSE EMPLOYEE_CURSOR;
END;