--recompile procedure
ALTER PROCEDURE RAISE_SALARY COMPILE;

--recompile function
ALTER FUNCTION CHECK_SALARY COMPILE;


--DROPPING PROCEDURE
DROP PROCEDURE RAISE_SALARY;

--DROPPING FUNCTION
DROP FUNCTION CHECK_SALARY;

