CREATE OR REPLACE FUNCTION GET_EMPLOYEE_LIST 
RETURN SYS_REFCURSOR 
IS 
    RESULT  SYS_REFCURSOR; 
BEGIN

    OPEN RESULT FOR
        SELECT * FROM EMPLOYEES;
    
    RETURN RESULT;
        
END;
----------------------------
