SET SERVEROUTPUT ON;

DECLARE 
    
    --DECLARE VARIABLES
    EMP_NAME    EMPLOYEES.FIRST_NAME%TYPE;
    EMP_SURNAME EMPLOYEES.LAST_NAME%TYPE;
    EMP_ID      EMPLOYEES.EMPLOYEE_ID%TYPE := &ENTER_ID; 

    --DECLARE SUBPROGRAMS
    PROCEDURE DISPLAY (MESSAGE VARCHAR2) IS
    
        PROC_MESSAGE    VARCHAR2(60);

    BEGIN
        IF LENGTH(MESSAGE) > 30 THEN
            PROC_MESSAGE := SUBSTR(MESSAGE , 1 ,30);
          ELSE
            PROC_MESSAGE := MESSAGE;
        END IF;
    
       dbms_output.put_line(PROC_MESSAGE);
    
    END DISPLAY;

BEGIN

    --RETRIEVE EMPLOYEE BY EMPLOYEE ID
    SELECT FIRST_NAME , LAST_NAME 
    INTO EMP_NAME , EMP_SURNAME
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = EMP_ID;

    DISPLAY ('EMPLOYEE:' || EMP_NAME || ' ' || EMP_SURNAME);

    EXCEPTION
        WHEN no_data_found or too_many_rows THEN
            DISPLAY('DATABASE ERROR');

        WHEN OTHERS THEN 
            DISPLAY('UNKNOWN EXCEPTION');

END MAINBLOCK;